config/routes.rb
Rails.application.routes.draw do

  resources :pay 
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :posts do 
      collection do 
        get 'upload'
      end
      member do 
        patch "commented"
        post "like"
        patch "sent"
      end 
  end

  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_voter
  has_many :posts

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

   before_action :load_user, only: [:edit, :show, :update,:destroy]
   def index
       @users = User.page params[:page]
   end
   def show

   end

   def edit

   end

   def destroy
      @user.destroy
      redirect_to admin_users_path, notice: '用户删除成功'
   end
   def update
      if @user.update user_params
          redirect_to current_user
      else
          render "edit"
      end
  end

   private
       def load_user
           @user = User.find(params[:id])
       end

      def user_params
        params.require(:user).permit(:id, :mobile_number,:name, :qq, :weixin, :avatar, :password, :password_confirmation)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :current_user

   def posts
     @posts = @current_user.posts
   end

end

app/views/users/posts.html.slim
table.table.table-hover 
  thead 
    th 序号
    th 图片
    th 状态
  tbody
    - @posts.each_with_index do | post, index |  
      tr
        td #{index+1}
        td 
          = link_to post_path(post) do 
            = image_tag "#{post.try(:photos).try(:first).try(:image).try(:thumb).try(:url)}", size: "64x64"
        td 
          - if post.sending?
            span.label.label-warning
              | #{post.chinese_status} 
          - else 
            span.label.label-default
              | #{post.chinese_status} 