config/routes.rb
Rails.application.routes.draw do

  resources :pay 
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :posts do 
      collection do 
        get 'upload'
      end
      member do 
        patch "commented"
        post "like"
        patch "sent"
      end 
  end

  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  

end

app/views/shared/_admin_navbar.html.slim
nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation"
    .container
      .navbar-header
          = link_to "我的@蔚县", root_url, class: "navbar-brand"
          button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'
                span.icon-bar
                span.icon-bar
                span.icon-bar
                span.icon-bar
      div class="collapse navbar-collapse"
         ul class="nav navbar-nav"
            li class="#{(params[:controller].end_with?('information') or params[:controller].end_with?('home'))? 'active':'' }"
              = link_to "信息", admin_information_index_path
            li class="#{params[:controller].end_with?('shops')?  'active':'' }"
              = link_to "商店",  admin_shops_path
            li class="#{params[:controller].end_with?('users')?  'active':'' }"
              = link_to "用户",  admin_users_path
            li class="#{params[:controller].end_with?('categories')?  'active':'' }"
              = link_to "类别",  admin_categories_path
         ul class="nav navbar-nav navbar-right"
            div class="collapse navbar-collapse"
               ul class="nav navbar-nav"

               ul class="nav navbar-nav navbar-right"
                  - if admin_signed_in?
                    li
                        = link_to "退出", destroy_admin_session_path, method: "delete"
                  - else
                    li
                        = link_to "注册", new_admin_registration_path
                    li
                        = link_to "登陆", new_admin_session_path

app/views/shared/_brand.html.slim
nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation"
    .container
      .navbar-header
          = link_to "蔚县@我", root_url, class: "navbar-brand"

app/views/shared/_flash_messages.html.slim
.container
  .row
    .col-md-12
        - flash.keys.each do |key|
          .alert class="alert-#{key}"
            = flash[key]
            button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;

app/views/shared/_footer.html.slim
.footer
    hr
    .container
       p.text-muted.text-center
          span.text-danger
              strong
                 | 继续前行，相信，生活会越来越好！

          span.hidden-xs   © 2015 Inc. &nbsp;

          a href="http://www.miitbeian.gov.cn/" class="hidden-xs"
            span.text-muted.small
              | 冀ICP备15004867

app/views/shared/_ie9.html.slim
/[if lt IE 9]
   script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
   script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"
   link href="http://static.yuxian.me/respond-proxy.html" id="respond-proxy" rel="respond-proxy"
   link href="/respond.proxy.gif" id="respond-redirect" rel="respond-redirect"
   script src="/respond.proxy.js"

/[if IE 10]
   = javascript_include_tag 'ie10-viewport-bug-workaround'
/[if IE]
   = javascript_include_tag 'ie-emulation-modes-warning'

app/views/shared/_ie_tip.html.slim
/[if lt IE 9]
  .container
    .row
      .col-lg-12
        p.alert.alert-warning
          | 十分抱歉，本站为提供更好的服务，不能很好的支持您正在使用的浏览器浏览本站，建议使用
          span.text-danger  
            strong IE9以上版本，或Chrome，FireFox 等浏览器最新版本，
          span.text-success
            | 可通过搜狗，百度等搜索下载

app/views/shared/_logo.html.slim
nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation"
    .container
      .navbar-header
          = link_to "蔚县@我", root_url, class: "navbar-brand"
          button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'
                span.icon-bar
                span.icon-bar
                span.icon-bar
      div class="collapse navbar-collapse"
         ul class="nav navbar-nav navbar-right"
            = render "shared/user_dropdown"

app/views/shared/_meta.html.slim
meta name="baidu-site-verification" content="hov3MzmVz6"
- if content_for?(:title)
    = yield :title
- else
    title = "送闲置"
meta name="keywords" content="#{meta_keywords}"
meta name="description" content="#{meta_description}"

meta charset='utf-8'
meta http-equiv='X-UA-Compatible' content='IE=edge'
meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"
meta name="apple-mobile-web-app-capable" content="yes"
meta name="mobile-web-app-capable" content="yes"
meta name="apple-mobile-web-app-title" content="送闲置"
meta content="email=no" name="format-detection"
meta property='wb:webmaster' content="78e9f2e1c609997f"


= favicon_link_tag 'logo.jpg'

app/views/shared/_my_location.html.slim
ol class="breadcrumb"
   li
     = link_to "首页", root_url
   li class="active"
     | Data

app/views/shared/_navbar.html.slim
nav id="navbar" class="navbar navbar-inverse navbar-fixed-bottom" role="navigation"
    .container
      .navbar-header
        button(class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar")
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"
      - unless params["controller"] == "posts" and (params["action"] == "new" or params["action"] == "create")
        .navbar-send
          = link_to "我要送", new_post_path, class:"btn btn-warning btn-send"
      #bs-navbar class="navbar-collapse collapse fade"
        ul class="nav navbar-nav pull-right"
           - unless @current_user.nil?
             li 
               = link_to "我的闲置", posts_user_path(@current_user) 
             //
              li class="#{( params[:controller].end_with?('information') or (params[:controller].end_with?('home') and params[:action].end_with?('index') ) )? 'active':'' }"
                a href="#information" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                 | 信息&nbsp;
                 span class="caret"
                ul class="dropdown-menu" role="menu"
                  - @categories.each do |category|
                    li
                      = link_to information_index_url(category_id: category.id) do

app/views/shared/_notice.html.slim
.container
  .row
    .col-md-12
        //
          - unless notice.blank?
            p class="notice alert alert-info"
                = notice
        - unless alert.blank?
          p class="alert alert-warning"
              = alert

app/views/shared/_session_navbar.html.slim
nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation"
    .container
      .navbar-header
          = link_to "我的", root_url, class: "navbar-brand"

      div class="collapse navbar-collapse"
         ul class="nav navbar-nav navbar-right"
              li
                  = link_to "登陆", new_user_session_path

app/views/shared/_user_dropdown.html.slim
- if user_signed_in?
  li.dropdown.my-dropdown
      = link_to  user_url(current_user), class: 'dropdown-toggle', "data-toggle"=> 'dropdown' do
         = image_tag("#{current_user.avatar.try(:thumb).url}", size: "20x20", alt: "touxiang ")
         | &nbsp; #{current_user.email} &nbsp;
         b.caret
      ul.dropdown-menu
         li
            = link_to  user_url(current_user) do
               span.glyphicon.glyphicon-folder-close
               | &nbsp; 我的资料
         li
            = link_to  i_information_index_url do
               span.glyphicon.glyphicon-info-sign
               | &nbsp; 我的信息

         li class="#{( params[:controller].end_with?('shops')  or params[:controller].end_with?('infos') ) ? 'active':''}"
           - if current_user.shop.nil?
             = link_to  guide_i_shops_path do
                span.glyphicon.glyphicon-shopping-cart
                | &nbsp; 我的商店
           - else
             = link_to i_shop_path(current_user.shop.id)
                 span.glyphicon.glyphicon-shopping-cart
                 | &nbsp; 我的商店

         li.divider
         li
           = link_to new_i_information_url do
             span.glyphicon.glyphicon-send
             |&nbsp; 发表信息

  li
      = link_to destroy_user_session_url, method: "delete" do
         span.glyphicon.glyphicon-log-out
         | 退出
- else
  li
      = link_to new_user_registration_url do
        span.glyphicon.glyphicon-registration-mark
        | &nbsp;注册
  li
      = link_to new_user_session_url do
         span.glyphicon.glyphicon-log-in
         | &nbsp; 登陆

app/views/shared/tmp.html.slim
div class="row fileupload-buttonbar"
  div class="col-lg-7"
    span class="btn btn-success fileinput-button"
      i class="glyphicon glyphicon-plus"
      span Add files...
      = f.input :image, as: :file,  input_html:{id:'fileupload',multiple:true, name:'picture[image]'}


    button type="submit" class="btn btn-primary start"
      i class="glyphicon glyphicon-upload"
      span Start upload

    button type="reset" class="btn btn-warning cancel"
      i class="glyphicon glyphicon-ban-circle"
      span Cancel upload

    button type="button" class="btn btn-danger delete"
      i class="glyphicon glyphicon-trash"
      span Delete

    input type="checkbox" class="toggle"

    span class="fileupload-process"


  div class="col-lg-5 fileupload-progress fade"

    div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100"
      div class="progress-bar progress-bar-success" style="width:0%;"


    div class="progress-extended">&nbsp;

  table role="presentation" class="table table-striped"
    tbody class="files"








  span class="btn btn-success fileinput-button"
    i class="glyphicon glyphicon-plus"
    span Add files...
    = f.input :image, as: :file,  input_html:{id:'fileupload',multiple:true, name:'picture[image]'}
    br
    br

    div id="progress" class="progress"
      div class="progress-bar progress-bar-success"

    div id="files" class="files"

script id="template-upload" type="text/x-tmpl"
  |
      {% for (var i=0, file; file=o.files[i]; i++) { %}
          <tr class="template-upload fade">
              <td>
                  <span class="preview"></span>
              </td>
              <td>
                  <p class="name">{%=file.name%}</p>
                  <strong class="error text-danger"></strong>
              </td>
              <td>
                  <p class="size">Processing...</p>
                  <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
              </td>
              <td>
                  {% if (!i && !o.options.autoUpload) { %}
                      <button class="btn btn-primary start" disabled>
                          <i class="glyphicon glyphicon-upload"></i>
                          <span>Start</span>
                      </button>
                  {% } %}
                  {% if (!i) { %}
                      <button class="btn btn-warning cancel">
                          <i class="glyphicon glyphicon-ban-circle"></i>
                          <span>Cancel</span>
                      </button>
                  {% } %}
              </td>
          </tr>
      {% } %}

script id="template-download" type="text/x-tmpl"
  |
      {% for (var i=0, file; file=o.files[i]; i++) { %}
          <tr class="template-download fade">
              <td>
                  <span class="preview">
                      {% if (file.thumbnailUrl) { %}
                          <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                      {% } %}
                  </span>
              </td>
              <td>
                  <p class="name">
                      {% if (file.url) { %}
                          <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                      {% } else { %}
                          <span>{%=file.name%}</span>
                      {% } %}
                  </p>
                  {% if (file.error) { %}
                      <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                  {% } %}
              </td>
              <td>
                  <span class="size">{%=o.formatFileSize(file.size)%}</span>
              </td>
              <td>
                  {% if (file.deleteUrl) { %}
                      <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                          <i class="glyphicon glyphicon-trash"></i>
                          <span>Delete</span>
                      </button>
                      <input type="checkbox" name="delete" value="1" class="toggle">
                  {% } else { %}
                      <button class="btn btn-warning cancel">
                          <i class="glyphicon glyphicon-ban-circle"></i>
                          <span>Cancel</span>
                      </button>
                  {% } %}
              </td>
          </tr>
      {% } %}





p
  |
       <form id="fileupload" action="http://jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
             <!-- Redirect browsers with JavaScript disabled to the origin page -->
             <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
             <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
             <div class="row fileupload-buttonbar">
               <div class="col-lg-7">
                 <!-- The fileinput-button span is used to style the file input field as button -->
                         <span class="btn btn-success fileinput-button">
                             <i class="glyphicon glyphicon-plus"></i>
                             <span>Add files...</span>
                             <input type="file" name="files[]" multiple>
                         </span>
                 <button type="submit" class="btn btn-primary start">
                   <i class="glyphicon glyphicon-upload"></i>
                   <span>Start upload</span>
                 </button>
                 <button type="reset" class="btn btn-warning cancel">
                   <i class="glyphicon glyphicon-ban-circle"></i>
                   <span>Cancel upload</span>
                 </button>
                 <button type="button" class="btn btn-danger delete">
                   <i class="glyphicon glyphicon-trash"></i>
                   <span>Delete</span>
                 </button>
                 <input type="checkbox" class="toggle">
                 <!-- The global file processing state -->
                 <span class="fileupload-process"></span>
               </div>
               <!-- The global progress state -->
               <div class="col-lg-5 fileupload-progress fade">
                 <!-- The global progress bar -->
                 <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                   <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                 </div>
                 <!-- The extended global progress state -->
                 <div class="progress-extended">&nbsp;</div>
               </div>
             </div>
             <!-- The table listing the files available for upload/download -->
             <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
           </form>