config/routes.rb
Rails.application.routes.draw do

  resources :pay 
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :posts do 
      collection do 
        get 'upload'
      end
      member do 
        patch "commented"
        post "like"
        patch "sent"
      end 
  end

  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  enum status: [:sending,:sent]
  acts_as_votable

  validates :description, presence:true
  has_many :photos, as: :imageable
  has_many :comments, as: :commentable
  validates :photos, presence:true

  belongs_to :user
  
  def chinese_status
    if self.sending?
      "正在送"
    else 
      "已送出"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   
   before_action  :authorize 
   before_action :current_user
   def index 

   end 

   def new 
     @post = Post.new
   end

   def show
     @post = Post.find(params[:id])
     @comment = Comment.new
     @comments = @post.comments.page params[:page]
     @voters = @post.votes_for.up.by_type(User).voters

     @share_data = Hash.new 
     @share_data[:img_url] = @post.photos.first.image.thumb.url
     @share_data[:title] = @post.description
     @share_data[:content] = @post.description
  
     share_url = share_link_url(post_url(@post))
     @share_data[:link] = share_url 

     @nocestr = Settings.nonce_str
     @timestamp = DateTime.now.to_i
     @app_id = "wx5940611bb6faccc3"
     @sign = signature(@nocestr,@timestamp,request.url) 
   end
    


   def commented
     @post = Post.find(params[:id])
     #  comment = Comment.new comment_params
     #  comment.user = @current_user

     @post.comments.create user: @current_user, content: comment_params[:content] 

     redirect_to @post
   end


   def upload
     @post = Post.new
     render "new"
   end

   def sent 
     @post = Post.find(params[:id])
     @post.sent!
     redirect_to @post
   end

   def edit

   end

   def update
   end
   def like
      @post = Post.find(params[:id])
      @has_voted = @current_user.voted_for? @post
      @has_voted ? @post.unliked_by(@current_user) : @post.liked_by(@current_user)
      @has_voted ? @has_voted = false : @has_voted = true
      @voters = @post.votes_for.up.by_type(User).voters
      @likes = @post.get_likes.size

   end

   def create
     
     @post = Post.new(post_params)
     unless post_params[:photo_ids].blank?
       photos = Photo.find(post_params[:photo_ids])
       @post.photos = photos
     end
     if @current_user.posts << @post and not @current_user.nil?
       @post.sending!
       redirect_to @post
     else
       render :new
     end

   end

   def post_params
     params.require(:post).permit(:id,:description,:photo_ids=>[])
   end
   def comment_params
     params.require(:comment).permit(:id, :content)
   end


end

app/views/posts/_form.html.slim
= simple_form_for @post,html:{multiple:true, id:"fileupload"} do |f|
  = f.error_notification
  - unless @post.errors[:photos].blank?
    .alert.alert-danger
      | 请至少上传一张照片! 少年
  = f.input :description, input_html:{class:'form-control'}
  = render "shared/posts/file_upload" 

  = f.submit "确定",  class: "btn btn-primary"

app/views/posts/like.js.erb
<% if @has_voted %>
  $("#favorite-icon").removeClass("fa-heart-o");
  $("#favorite-icon").addClass("fa-heart");
  //$('#favorite-icon').animo( { animation: ['tada'], duration: 2 } );
<% else %>
  $("#favorite-icon").removeClass("fa-heart");
  $("#favorite-icon").addClass("fa-heart-o");
  //$('#favorite-icon').animo( { animation: ['tada', 'bounce'], duration: 2 } );
<% end %>

var votersHtml = ""
<% @voters.each do |voter| %>
  var tmp ='<a href="#"><img src="<%= voter.headimgurl%>" class="wanted-head"/></a>';
  votersHtml = votersHtml + tmp
  
  $(".voters").html(votersHtml);
<% end %>

<% if @voters.size == 0 %>

  $(".voters").html("");
<% end %>

$(".like-count").html('<%= @likes %>');

app/views/posts/new.html.slim
= render "form"
= render "shared/posts/upload"

app/views/posts/show.html.slim
#posts-show
  
  .media 
    .media-left
      a href="#"
        img class="media-object media-head" src="#{@post.try(:user).try(:headimgurl)}" 

    .media-body
      h4.media-heading #{@post.user.nickname}
      p #{@post.description}
      
      - @post.photos.each do | photo | 
        a href="#{photo.image.url}" title="#{photo.image.file.filename}" download="#{photo.image.file.filename}" data-gallery="data-gallery"
          img class="img-thumbnail img-inline" src="#{photo.image.try(:thumb).try(:url)}"
      p
        small.text-muted #{time_ago_in_words @post.created_at}
      p
        - if @post.sent? 
          span.label.label-default 已送出
        - if @post.sending? and !@curent_user.nil? and  @current_user.id == @post.user.id 
          = link_to "已送出", sent_post_path(@post), method: :patch,class: "btn btn-danger"

      p
      .like-area
        .like-opt
          - unless @current_user.nil?
            span.label.label-success 想要
            = link_to like_post_path(@post), class: "favorite-btn", method: "post", remote: true do
              span.favorite-span
                  - if @current_user.voted_for? @post
                    i id="favorite-icon" class="fa fa-heart favorite-heart"
                  - else
                    i id="favorite-icon" class="fa fa-heart-o favorite-heart"
                  //
                    span.like-count #{@post.get_likes.size}
        .voters 
          - @voters.each do |voter|    
            a(herf="#user")
              img src="#{voter.headimgurl}" class="wanted-head"

  p
    #comment-modal.modal.fade.bs-example-modal-lg
      .modal-dialog.modal-lg
        .modal-content
           = simple_form_for @comment, url: commented_post_path(@post), method:"patch" do |f|
            .modal-body
                = f.error_notification
                = f.input :content, label:false, as: :text, input_html:{rows:10}
            .modal-footer
                
                = f.submit '评',class:"btn btn-primary"
                button type="button" class="btn btn-default" data-dismiss="modal" 取消


  hr
  .row
   .col-xs-3
     .comments-text 评论 
   .col-xs-3.col-xs-offset-6
      a(href="#comment-modal" class="comments-btn" data-toggle="modal" data-target="#comment-modal")
        i.fa.fa-comments
  - @comments.each do | comment |
      .media 
        .media-left
          a href="#"
            img class="media-object comments-head" src="#{comment.user.try(:headimgurl)}" 

        .media-body
          p
       
            | #{comment.content}
          p.pull-right
            small #{comment.user.nickname}
            span &nbsp;&nbsp;
            small.text-muted #{time_ago_in_words comment.created_at}

  p 
  .row
   .col-lg-12.toolbar
        .pull-right = paginate @comments, theme: 'twitter-bootstrap-3'

  input id="share-url" type="hidden" value="#{@share_data[:link]}"
  input id="share-title" type="hidden" value="#{@share_data[:title]}"
  input id="share-content" type="hidden" value="#{@share_data[:content]}"
  input id="share-image-url" type="hidden" value="#{@share_data[:img_url]}"
  input id="noncestr" type="hidden" value="#{@nocestr}"
  input id="timestamp" type="hidden" value="#{@timestamp}"
  input id="sign" type="hidden" value="#{@sign}"
  input id="app-id" type="hidden" value="#{@app_id}"

  = render "shared/posts/gallery"