config/routes.rb
Rails.application.routes.draw do

  resources :pay 
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :posts do 
      collection do 
        get 'upload'
      end
      member do 
        patch "commented"
        post "like"
        patch "sent"
      end 
  end

  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  enum status: [:sending,:sent]
  acts_as_votable

  validates :description, presence:true
  has_many :photos, as: :imageable
  has_many :comments, as: :commentable
  validates :photos, presence:true

  belongs_to :user
  
  def chinese_status
    if self.sending?
      "正在送"
    else 
      "已送出"
    end
  end
end

app/controllers/admin/information_controller.rb
class Admin::InformationController < Admin::AdminController

  before_action :set_information, only: [:show, :destroy, :edit, :update]

  def index
    @information = Information.page params[:page]
  end

  def edit

  end

  # PATCH/PUT /information/1
  def update
    if @information.update(information_params)
      redirect_to admin_information_index_path, notice: '信息更新成功'
    else
      render :edit
    end
  end

   # DELETE /information/1
  def destroy
    @information.destroy
    redirect_to admin_information_index_path, notice: '信息删除成功'
  end
  # GET /information/1
  def show

  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_information
    @information = Information.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def information_params
    params.require(:information).permit(:id, :title, :description, :publish,:image, :price, :contact, :mobile_number, :qq, :weixin, :category_id)
  end
end

app/controllers/i/information_controller.rb
class I::InformationController < I::BaseController

  before_action :set_information, only: [:show, :edit, :update, :destroy,:display]

  # GET /information
  def index
    @information = current_user.information.page params[:page]
  end

  # GET /information/1
  def show

  end


  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  def create

    @information = Information.new(information_params)

    unless information_params[:photo_ids].blank?
      photos = Photo.find(information_params[:photo_ids])
      @information.photos = photos
    end

    if current_user.information  <<  @information
      # redirect_to [:i,@information], notice: '信息创建成功'
       redirect_to i_information_index_path, notice: '信息创建成功'
    else
      render :new
    end
  end

  # PATCH/PUT /information/1
  def update
    if @information.update(information_params)
      @information.update_synchronized_at
      redirect_to i_information_index_path, notice: '信息更新成功'
    else
      render :edit
    end
  end

  # DELETE /information/1
  def destroy
    @information.destroy
    redirect_to i_information_index_path, notice: '信息删除成功'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_information
    @information = Information.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def information_params
    params.require(:information).permit(:id, :title, :description, :publish,:image, :price, :contact, :mobile_number, :qq, :weixin, :category_id, :photo_ids=>[])
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController

  before_action :set_information, only: [:show,:like, :commented]

  skip_before_filter :verify_authenticity_token, :only => [:like]

  def index
    @category = Category.find(params[:category_id])
    @information = Information.where(publish:true,category: @category).page params[:page]
  end

  def show
    #binding.pry
    @comment = Comment.new # @information.comments.build
    @category = Category.find(params[:category_id]) unless params[:category_id].nil?
    @comments = @information.comments.page params[:page]
    @information.increment_visit_count
  end

  def like

    #current_user.likes @information unless current_user.nil?

    @has_voted = current_user.voted_for? @information
    @has_voted ? @information.unliked_by(current_user) : @information.liked_by(current_user)
    @has_voted ? @has_voted = false : @has_voted = true
    @likes = @information.get_likes.size

  end

  def commented
    @comment = Comment.new comment_params

    @comment.user_id = current_user.id
    ###comment.save
    if @information.comments << @comment
      #@comment = Comment.new
    end
    #@category = @information.category
    #@comments = @information.comments.page params[:page]

    #render "show"
    redirect_to information_path(@information)
  end



  def comment_params
    params.require(:comment).permit(:id, :content)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_information

    @information = Information.find(params[:id])
  end


end

app/views/shared/information/_file_upload.html.slim
.row
  .col-md-4
    #dropzone
      | 拖动文件到此区域可上传
p

div class="row fileupload-buttonbar"
  div class="col-lg-2"
    span class="btn btn-success fileinput-button"
      i class="glyphicon glyphicon-plus"
      span
        | 上传图片
      input type="file" name="photo[image]" multiple="true"

    //
      button type="submit" class="btn btn-primary start"
        i class="glyphicon glyphicon-upload"
        span
      button type="reset" class="btn btn-warning cancel"
        i class="glyphicon glyphicon-ban-circle"
        span Cancel upload
      button type="button" class="btn btn-danger delete"
        i class="glyphicon glyphicon-trash"
        span Delete
      input type="checkbox" class="toggle"

    span class="fileupload-process"


  div class="col-lg-10 fileupload-progress fade"

    div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100"
      div class="progress-bar progress-bar-success" style="width:0%;"


    div class="progress-extended">&nbsp;

.row
  .col-lg-12
    table role="presentation" class="table table-striped"
      tbody class="files"

        - @information.photos.each  do |photo|
          - unless photo.image.url.blank?
            tr class="template-download in"
              td
                span class="preview"
                  input name="information[photo_ids][]" type="hidden" value="#{photo.id}"
                  a href="#{photo.image.url}" title="#{photo.image.file.filename}" download="#{photo.image.file.filename}" data-gallery="data-gallery"
                    img src="#{photo.image.try(:thumb).url}" class="img-thumbnail"

              td
                p class="name"
                  a href="#{photo.image.url}" title="#{photo.image.file.filename}" download="#{photo.image.file.filename}" data-gallery="data-gallery"
                    span = "#{photo.image.file.filename}"
              td
                - if photo.cover
                  span class="label label-success cover-span fade in" 当前封面
                - else
                  span class="label label-success cover-span fade" 当前封面

              td
                span class="size"
                  | #{human_file_size(photo.image.size)}
              td
                - if photo.cover
                  input type="button" id="#{photo.id}" class="btn btn-info cover-binding fade" value="设为封面"
                - else
                  input type="button" id="#{photo.id}" class="btn btn-info cover-binding" value="设为封面"
                button class="btn btn-danger delete" data-type="DELETE" data-url="#{photo_path(photo)}"
                  i class="glyphicon glyphicon-trash"
                  span 删除